parameters:
    anh_pager.pager_length: 10
    anh_pager.pager.class: Anh\PagerBundle\Pager

services:
    anh_pager.pager:
        class: %anh_pager.pager.class%
        arguments: [ %anh_pager.pager_length% ]
